name: 'Branch Validator'
description: 'Validates branches against a pre-defined pattern'
author: 'Tom Sacher'
inputs:
  scopes:
    required: false
    description: 'Specify all the scopes that are allowed before the slash'
    default: 'fix,feat,build,chore,ci,docs,style,refactor,perf,test'
outputs:
  branch:
    description: 'The PRs branch name'
runs:
  using: 'node16'
  main: 'dist/index.js'
